Update 贡献者认证流程.md
sibbay-ai/public pull request #192
Opened 2018-03-21 10:55 UTC by maohuaming

for : issue https://github.com/sibbay-ai/public/issues/191
更新贡献者认证流程文档的内容，增加了认证规则。
@fushang318 请评审。

2018-03-21 14:27 UTC, fushang318 requested changes

2018-03-21 14:27 UTC, fushang318 commented on 贡献者认证流程.md
> +贡献者认证流程|[贡献者认证流程文档链接](https://github.com/sibbay-ai/public/blob/master/%E8%B4%A1%E7%8C%AE%E8%80%85%E8%AE%A4%E8%AF%81%E6%B5%81%E7%A8%8B.md)
@maohuaming 这一行可以去掉啦，不用自己链接自己

2018-03-22 02:35 UTC, georgeliuyu reviewed
增加必须提问的列表。

2018-03-22 02:35 UTC, georgeliuyu commented on 贡献者认证流程.md
>  可由申请者自行或者 mentor 在 public 中创建认证 issue。
- 由committer建立icp 认证流程申请 issue ，@人事  
- 有人事进行电话沟通后确认奖励标准，@认证人员
- 完成后@发起人

2018-03-22 02:54 UTC, georgeliuyu commented
@maohuaming 
![image](https://user-images.githubusercontent.com/16983441/37748504-0d0da320-2dbf-11e8-9296-ff7323586657.png)

2018-03-22 07:31 UTC, fushang318 commented on 贡献者认证流程.md
>  可由申请者自行或者 mentor 在 public 中创建认证 issue。
@maohuaming 
按照 @georgeliuyu 的意见，这个应该删除吧？
只能由 committer 建立 icp认证 issue

2018-03-22 07:40 UTC, georgeliuyu commented
@maohuaming @fushang318 最近public的pr由我来merge

2018-03-22 07:49 UTC, fushang318 commented
@georgeliuyu 好的，明白啦

2018-03-22 09:36 UTC, maohuaming commented on 贡献者认证流程.md
>  可由申请者自行或者 mentor 在 public 中创建认证 issue。
@georgeliuyu 刘总，跟您确认一下，您要求“增加必须提问的列表”，这个是指在文档中列出ICP理解测试issue中要提问的问题列表吗？

2018-03-23 02:02 UTC, georgeliuyu commented on 贡献者认证流程.md
>  可由申请者自行或者 mentor 在 public 中创建认证 issue。
@maohuaming 对的

2018-03-23 02:48 UTC, maohuaming commented on 贡献者认证流程.md
>  可由申请者自行或者 mentor 在 public 中创建认证 issue。
@georgeliuyu 收到，明白。

2018-03-23 05:47 UTC, maohuaming commented
@georgeliuyu 已按照评审意见修改了文件内容。请评审。

2018-03-23 06:09 UTC, georgeliuyu commented
@maohuaming commit要rebase为1

2018-03-23 06:11 UTC, fushang318 submitted a review, later dismissed

2018-03-23 07:47 UTC, maohuaming commented
@georgeliuyu committer要rebase为1的话，github网页版的操作就只有“Rebase and merge”这个选项可以用。不过rebase的同时也做了merge操作，是否由我来做这个操作？

2018-03-23 08:46 UTC, georgeliuyu commented
@maohuaming 你可以用命令行操作啊！

2018-03-23 08:47 UTC, georgeliuyu commented
@maohuaming icp认证中看到这样的提交（技术人员）是不能通过的。

2018-03-30 03:41 UTC, maohuaming commented
@georgeliuyu 已经将commit rebase为1，请处理。

2018-03-31 05:49 UTC, georgeliuyu approved these changes

2018-04-01 01:23 UTC, fushang318 approved these changes

2018-04-01 01:23 UTC, merged