icp流程的整理和文档完善
sibbay-ai/public pull request #268
Opened 2018-04-09 02:57 UTC by georgeliuyu

1、将核心icp流程的内容合并到readme中；
2、删除了内容重复的内容；
3、增加了deadline的执行细则；
4、对EI的进行了说明；
预推行试讲4月15日

@sibbay-ai/all 请大家仔细阅读，有疑问可在issue中提出。会安排统一的时间进行解答。有建议也希望能有详细的描述。
第一次说明会安排在4月11日晚9:00的站会。

2018-04-09 03:11 UTC, fushang318 commented on 贡献者认证流程.md
> +## 4、小白社区贡献者ICP流程认证培训文档清单
这一大项可以删除了，README里的其他中已经列出来了

2018-04-09 03:13 UTC, fushang318 commented on README.md
> +|icp FAQ|[ICP入门FAQ文档链接](https://github.com/sibbay-ai/public/blob/master/icp%E5%85%A5%E9%97%A8FAQ.md)|
这里合并后链接就不对了，因为该文件在这个PR里改名字了

2018-04-09 03:14 UTC, fushang318 commented on README.md
> +|icp FAQ|[ICP入门FAQ文档链接](https://github.com/sibbay-ai/public/blob/master/icp%E5%85%A5%E9%97%A8FAQ.md)|
这里合并后链接就不对了，因为该文件在这个PR里改名字了

2018-04-09 06:43 UTC, maohuaming commented on icp FAQ.md
> +## 7、没有项目的代码仓库有权限怎么办？
此处有语病，应改为：“没有项目代码仓库的权限怎么办？”

2018-04-09 06:43 UTC, maohuaming commented on README.md
> +任何pr都必须由非提交者进行review。
如果是review类型的issue，提交pr时 ，是否需要review？

2018-04-09 07:00 UTC, fushang318 commented on README.md
> +任何pr都必须由非提交者进行review。
@maohuaming review 类型的 issue ,不需要提交PR，只需要把 issue 关联到 review 的 pr 中，当然这个关联需要按照有效引用的规则来

2018-04-11 06:49 UTC, fushang318 requested changes

2018-04-11 06:49 UTC, fushang318 commented on README.md
> +变更 deadline:yyyy-mm-dd [@xx] 变更原因
@ 也应该是必须的

2018-04-11 06:49 UTC, fushang318 commented on README.md
> +申请开发 deadline:yyyy-mm-dd size:xx [@xxx] [文字]
@ 应该是必须的

2018-04-11 06:49 UTC, fushang318 commented on README.md
> +- 一个pr原则上只建议一个assigness
一个PR只能由一个 ASSIGNESS

2018-04-11 06:49 UTC, fushang318 commented on README.md
> +- starttime是以提出申请的comment的时间为准，如果contributer认为committer的确认回复太晚会影响deadline的完成，应该马上申请修改deadline。
这个月没法统计 ti 了，因为没有办法精确的知道 starttime  
建议从下个月开始计算 ti

2018-04-11 15:37 UTC, fushang318 commented on README.md
> +- 建议你仔细阅读 https://github.com/sibbay-ai/public下的issue（包括close的issue）
超级链接和后边的文字加个空格，不然格式不对

2018-04-11 15:37 UTC, fushang318 commented on README.md
> +- 建议你观摩小白社区的早会，地址是：https://zoom.us/j/9552592803，以了解团队的工作方式
超级链接和后边的逗号加个空格，不然格式不对

2018-04-12 01:33 UTC, georgeliuyu commented on README.md
> +- starttime是以提出申请的comment的时间为准，如果contributer认为committer的确认回复太晚会影响deadline的完成，应该马上申请修改deadline。
同意

2018-04-12 09:05 UTC, fushang318 commented on README.md
> +- 建议你观摩小白社区的早会，地址是：https://zoom.us/j/9552592803，以了解团队的工作方式
地址是：https://zoom.us/j/9552592803，以了解团队的工作方式

改成

地址是：https://zoom.us/j/9552592803  ，以了解团队的工作方式

2018-04-12 17:19 UTC, sinchb requested changes

2018-04-12 17:19 UTC, sinchb commented on README.md
> +社区建议并鼓励贡献者在做任何事情是均以创建issue为开始，并@给相关committer或者contributor。
"任何事情是均以"

改为
"任何事情时均以"

@georgeliuyu

2018-04-12 17:19 UTC, sinchb commented on README.md
> +申请开发 deadline:yyyy-mm-dd size:xx [@xxx] [文字]
申请开发是在前面么，我记得deadline在前面 @fushang318 @georgeliuyu

2018-04-12 17:19 UTC, sinchb commented on README.md
> +- 理论上社区认为review耗费的size越大，提交的成果质量则越差
这条我保留意见，一般来说review所需要的时间，和pr的长短、形式和内容相关，有些则需要和提交者进行沟通。 @georgeliuyu @fushang318 @ben7th @ax003d

2018-04-12 17:19 UTC, sinchb commented on README.md
> +以提交物为目标的**直接**努力均可计入size。标准以该领域熟练人员正常完成所需的时间长度。
"标准以该领域熟练人员正常完成所需的时间长度。  "

改为

"标准以该领域熟练人员正常完成所需的时间长度 **为准**。  "

@georgeliuyu

2018-04-12 17:19 UTC, sinchb commented on 通讯录.md
> +|[@sinchb](https://github.com/sinchb)| 陈斌 | 小程序后端开发、维护， |正常|
这个 "，" 可以去掉。。 @georgeliuyu

2018-04-13 01:59 UTC, georgeliuyu commented on README.md
> +- 理论上社区认为review耗费的size越大，提交的成果质量则越差
在相同的类型提交物，由相同人员review的条件下，review所耗费size越大则可推断为提交物的质量越差的概率会非常大；
另外之这一条的核心目的是提醒大家要尽量考虑周全，尽量使得review工作量减小。

2018-04-13 02:03 UTC, georgeliuyu commented on README.md
> +申请开发 deadline:yyyy-mm-dd size:xx [@xxx] [文字]
@fushang318 @可以不强求
@sinchb 对在前面

2018-04-13 02:08 UTC, georgeliuyu commented on README.md
> +申请开发 deadline:yyyy-mm-dd size:xx [@xxx] [文字]
会存在自己是committer的情况，不用@自己 @fushang318

2018-04-13 02:22 UTC, fushang318 approved these changes

2018-04-13 03:38 UTC, sinchb approved these changes

2018-04-13 03:40 UTC, sinchb commented on README.md
> +- 理论上社区认为review耗费的size越大，提交的成果质量则越差
这个似乎没有证明。如果一个pr非常大，reviewer需要仔细阅读代码，那么就是需要比较多的时间，这花费了reviewer的时间，并且也是出于尊重和负责。我建议使用request changes的次数来衡量，而不是用reviewer的size来衡量。 @georgeliuyu

2018-04-13 03:41 UTC, merged