Update 目标.md
sibbay-ai/public pull request #294
Opened 2018-04-19 06:53 UTC by georgeliuyu

2018-04-19 06:54 UTC, Yidadaa approved these changes

2018-04-19 06:55 UTC, Yidadaa requested changes
@Yidadaa 的w15目标状态应为完成。

2018-04-19 07:10 UTC, ax003d submitted a review, later dismissed

2018-04-20 01:17 UTC, georgeliuyu commented
@Yidadaa 抱歉，写错了。已修改。

2018-04-20 07:06 UTC, fushang318 commented
@georgeliuyu 没有引用 ISSUE，其他没问题

2018-04-20 07:07 UTC, georgeliuyu commented
for #269 
for #273 
for #274 
for #276

2018-04-20 07:08 UTC, fushang318 approved these changes

2018-04-20 07:09 UTC, Yidadaa approved these changes

2018-04-20 07:11 UTC, merged