Feature/ly add faq
sibbay-ai/public pull request #53
Opened 2017-12-14 07:11 UTC by georgeliuyu

增加了mentor机制的说明，请注意review

2017-12-14 07:17 UTC, fushang318 approved these changes

2017-12-14 07:37 UTC, sinchb approved these changes

2017-12-14 07:46 UTC, ben7th requested changes
commit 需要 rebase 成一个

2017-12-14 07:46 UTC, ben7th commented on README.md
> +
好像没有一个地方给 mentor 单独给出释义

2017-12-14 13:34 UTC, sinchb commented
这里有个选项 
![image](https://user-images.githubusercontent.com/1590268/33994711-93b9acac-e116-11e7-824e-b9bd47f7a185.png)

2017-12-15 00:09 UTC, fushang318 commented
@sinchb 额，原来有这个功能，以前没注意过，这个就方便多了呀

2017-12-15 02:04 UTC, georgeliuyu commented
@ben7th rebase为一个commit，同时更加了mentor的说明

2017-12-15 08:21 UTC, ben7th approved these changes

2017-12-15 08:22 UTC, merged

2017-12-15 14:48 UTC, sinchb commented
![image](https://user-images.githubusercontent.com/1590268/34047058-fe7b5cd8-e1e9-11e7-83f4-1fb6c2b6c725.png)

@georgeliuyu @ben7th @fushang318 这个好像还是不太合规矩

2017-12-17 02:20 UTC, georgeliuyu commented
@sinchb 是，以后注意